  
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  spring:
    image: qac1978/seguituscompras_backend:latest
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_DOCKER}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      FRONT_ORIGIN: ${FRONT_ORIGIN_DOCKER}
      PROFILE: ${PROFILE}
    depends_on:
      - postgres
    ports:
      - "8080:8080" # Es necesario para que funcione que esto se levante en el 8080

  frontend:
    image: qac1978/seguituscompras_frontend:latest
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - spring
    container_name: segui-tus-compras










  
