  
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_grupo2
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  spring:
    image: qac1978/seguituscompras_backend:latest
    container_name: backend_container_grupo2
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_DOCKER}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      FRONT_ORIGIN: ${FRONT_ORIGIN_DOCKER}
      PROFILE: stg
    depends_on:
      - postgres
    ports:
      - "8080:8080" # Es necesario para que funcione que esto se levante en el 8080

  frontend:
    image: qac1978/seguituscompras_frontend:latest
    container_name: frontend_container_grupo2
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - spring
  
  k6:
    image: grafana/k6
    container_name: k6_grupo2
    volumes:
      - ./k6:/k6 
    working_dir: /k6
    command: ["sleep", "infinity"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_grupo2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - spring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_grupo2
    ports:
      - "2000:3000"
    depends_on:
      - prometheus
    volumes:
    - grafana_data:/var/lib/grafana
volumes:
  grafana_data:










  
